---
title: 'Axis'
author: 'Sofia'
date: '2024/11/25'
toc: true
format:
  html:
    embed-resources: true

---

## 1. Box plot

- Draw a boxplot using `PlantGrowth` dataset.
- `Labs()` function is to add title, axis labels, and caption.

```{r}
library(ggplot2)

ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot() +
  labs(title = 'Group vs Weight',
       x = 'Group',
       y = 'Weight',
       caption = 'By Sofia, DV, THU, 2024') +
  theme(plot.title = element_text(hjust = 0.5, size=20))
```

## 2. Swap X and Y axes

```{r}
library(ggplot2)

ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot() +
  coord_flip() +
  labs(title = 'Weight vs Group',
      x = 'Weight',
      y = 'Group',
      caption = 'By Sofia, DV, THU, 2024') +
  theme(plot.title = element_text(hjust = 0.5, size=20))
```

## 3. Arrange two plots side by side

```{r}
library(ggplot2)
library(gridExtra)

p1 <- ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot() +
  labs(title = 'Group vs Weight',
       x = 'Group',
       y = 'Weight',
       caption = 'By Sofia, DV, THU, 2024') +
  theme(plot.title = element_text(hjust = 0.5, size=20))

p2 <- ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_boxplot() +
  coord_flip() +
  labs(title = 'Weight vs Group',
      x = 'Weight',
      y = 'Group',
      caption = 'By Sofia, DV, THU, 2024') +
  theme(plot.title = element_text(hjust = 0.5, size=20))

grid.arrange(p1, p2, ncol = 2,
             top = 'Arrange two plots side by side')
```